external_components:
  - source: github://pfriedrich84/esphome-elero

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

elero:
  cs_pin: GPIO5
  gdo0_pin: GPIO26
  freq0: 0xc0
  freq1: 0x71
  freq2: 0x21

cover:
  - platform: elero
    blind_address: 0xa831e5
    channel: 4
    remote_address: 0xf0d008
    name: Schlafzimmer
    open_duration: 25s
    close_duration: 22s

# RSSI sensor - reports signal strength for a specific blind
sensor:
  - platform: elero
    blind_address: 0xa831e5
    name: "Schlafzimmer RSSI"

# Text sensor - reports blind state as text (top, bottom, moving_up, etc.)
text_sensor:
  - platform: elero
    blind_address: 0xa831e5
    name: "Schlafzimmer Status"

# Buttons for RF discovery scan
button:
  - platform: elero
    name: "Elero Start Scan"
    scan_start: true
  - platform: elero
    name: "Elero Stop Scan"
    scan_start: false

# HTTP server (auto-loaded by elero_web; no default ESPHome UI, only /elero is served)
# Do NOT use web_server: here — it would re-enable the unwanted default UI at /
web_server_base:
  port: 80

elero_web:
  id: elero_web_ui

# Home Assistant switch to enable / disable the web UI at runtime.
# When off, all /elero routes return 503 and no RF state is served.
switch:
  - platform: elero_web
    name: "Elero Web UI"
    id: elero_web_switch
    restore_mode: RESTORE_DEFAULT_ON
