import logging
from pathlib import Path

import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components.elero import CONF_ELERO_ID, elero, elero_ns
from esphome.components.logger import request_log_listener
from esphome.const import CONF_ID, CONF_PORT

_LOGGER = logging.getLogger(__name__)

DEPENDENCIES = ["elero", "network", "logger"]
AUTO_LOAD = ["json"]
CODEOWNERS = ["@manuschillerdev"]

# Exported so the switch sub-platform can reference the web server class
CONF_ELERO_WEB_ID = "elero_web_id"
EleroWebServer = elero_ns.class_("EleroWebServer", cg.Component)

CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(): cv.declare_id(EleroWebServer),
        cv.GenerateID(CONF_ELERO_ID): cv.use_id(elero),
        cv.Optional(CONF_PORT, default=80): cv.port,
    }
).extend(cv.COMPONENT_SCHEMA)

# elero_web_ui.h is generated by the Vite build plugin (vite.config.ts).
# Run 'cd components/elero_web/frontend/app && pnpm build' to regenerate.
_UI_HEADER = Path(__file__).parent / "elero_web_ui.h"


async def to_code(config):
    if not _UI_HEADER.exists():
        _LOGGER.warning(
            "Frontend header not found: %s. "
            "Run 'cd components/elero_web/frontend/app && pnpm build' first.",
            _UI_HEADER,
        )

    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)

    parent = await cg.get_variable(config[CONF_ELERO_ID])
    cg.add(var.set_elero_parent(parent))
    cg.add(var.set_port(config[CONF_PORT]))

    # Request log listener support for forwarding logs to WebSocket
    request_log_listener()
