import logging
from pathlib import Path

import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components.elero import CONF_ELERO_ID, CONF_REGISTRY_ID, ELERO_VERSION, DeviceRegistry, elero, elero_ns
from esphome.components.logger import request_log_listener
from esphome.const import CONF_ID, CONF_PORT

_LOGGER = logging.getLogger(__name__)

DEPENDENCIES = ["elero", "network", "logger"]
AUTO_LOAD = ["json"]
CODEOWNERS = ["@manuschillerdev"]

# Mongoose version pinned for reproducible builds
_MONGOOSE_VERSION = "7.20"
_MONGOOSE_BASE_URL = (
    f"https://raw.githubusercontent.com/cesanta/mongoose/{_MONGOOSE_VERSION}"
)
_MONGOOSE_FILES = ("mongoose.h", "mongoose.c")
_COMPONENT_DIR = Path(__file__).parent

_GITHUB_REPO = "manuschillerdev/esphome-elero"
_UI_HEADER_FILENAME = "elero_web_ui.h"

# Exported so the switch sub-platform can reference the web server class
CONF_ELERO_WEB_ID = "elero_web_id"
EleroWebServer = elero_ns.class_("EleroWebServer", cg.Component)

CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(): cv.declare_id(EleroWebServer),
        cv.GenerateID(CONF_ELERO_ID): cv.use_id(elero),
        cv.GenerateID(CONF_REGISTRY_ID): cv.use_id(DeviceRegistry),
        cv.Optional(CONF_PORT, default=80): cv.port,
    }
).extend(cv.COMPONENT_SCHEMA)

# elero_web_ui.h is generated by the Vite build plugin (vite.config.ts).
# For local dev: cd components/elero_web/frontend/app && pnpm build
# For releases: downloaded automatically from GitHub release assets.
_UI_HEADER = _COMPONENT_DIR / _UI_HEADER_FILENAME


def _ensure_mongoose():
    """Download mongoose amalgamated files if not already present."""
    import urllib.request

    for filename in _MONGOOSE_FILES:
        target = _COMPONENT_DIR / filename
        if target.exists():
            continue
        url = f"{_MONGOOSE_BASE_URL}/{filename}"
        _LOGGER.info("Downloading mongoose %s from %s", _MONGOOSE_VERSION, url)
        urllib.request.urlretrieve(url, target)


def _ensure_ui_header():
    """Download the pre-built frontend header from the GitHub release."""
    if _UI_HEADER.exists():
        return

    import urllib.request

    url = (
        f"https://github.com/{_GITHUB_REPO}/releases/download/"
        f"v{ELERO_VERSION}/{_UI_HEADER_FILENAME}"
    )
    _LOGGER.info(
        "Downloading pre-built frontend (v%s) from %s", ELERO_VERSION, url
    )
    try:
        urllib.request.urlretrieve(url, _UI_HEADER)
    except Exception:
        _LOGGER.warning(
            "Could not download %s — the web UI will not be available. "
            "For local development, run: "
            "cd components/elero_web/frontend/app && pnpm build",
            _UI_HEADER_FILENAME,
        )


async def to_code(config):
    _ensure_ui_header()

    # Download mongoose amalgamated files (gitignored, not vendored)
    _ensure_mongoose()

    # Mongoose build config — defines go into ESPHome's defines.h
    # MG_ARCH must be a build flag because cg.add_define() wraps string
    # values in quotes, but MG_ARCH_ESP32 is a macro that expands to an int.
    cg.add_build_flag("-DMG_ARCH=MG_ARCH_ESP32")
    cg.add_define("MG_ENABLE_HTTP", 1)
    cg.add_define("MG_ENABLE_WEBSOCKET", 1)
    cg.add_define("MG_ENABLE_MQTT", 0)
    cg.add_define("MG_ENABLE_DNS", 0)
    cg.add_define("MG_ENABLE_IPV6", 0)
    cg.add_define("MG_ENABLE_FILE", 0)
    cg.add_define("MG_ENABLE_DIRECTORY_LISTING", 0)
    cg.add_define("MG_ENABLE_SSI", 0)
    cg.add_define("MG_ENABLE_CUSTOM_RANDOM", 0)
    cg.add_define("MG_ENABLE_PACKED_FS", 0)
    cg.add_define("MG_ENABLE_TLS", 0)
    cg.add_define("MG_IO_SIZE", 512)
    # Build flag ensures mongoose.c sees this before its own default (#ifndef guard)
    cg.add_build_flag("-DMG_ENABLE_LOG=0")

    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)

    parent = await cg.get_variable(config[CONF_ELERO_ID])
    cg.add(var.set_elero_parent(parent))
    cg.add(var.set_port(config[CONF_PORT]))

    # Register as output adapter for state_changed events (optimistic updates)
    registry = await cg.get_variable(config[CONF_REGISTRY_ID])
    cg.add(registry.add_adapter(var))

    # Request log listener support for forwarding logs to WebSocket
    request_log_listener()
