import { defineConfig, type Plugin } from 'vite'
import preact from '@preact/preset-vite'
import tailwindcss from '@tailwindcss/vite'
import { viteSingleFile } from 'vite-plugin-singlefile'
import { resolve } from 'path'
import { readFileSync, writeFileSync } from 'fs'
import { gzipSync } from 'zlib'

// Use DEVICE_IP env var to connect to real device, otherwise use mock server
// Example: DEVICE_IP=192.168.1.100 pnpm dev
const deviceTarget = process.env.DEVICE_IP
  ? `ws://${process.env.DEVICE_IP}`
  : 'ws://localhost:8080'

function eleroGzipHeader(): Plugin {
  return {
    name: 'elero-gzip-header',
    apply: 'build',
    closeBundle() {
      const htmlPath = resolve(import.meta.dirname, 'dist/index.html')
      const headerPath = resolve(import.meta.dirname, '../../elero_web_ui.h')

      const html = readFileSync(htmlPath)
      const gz = gzipSync(html, { level: 9 })

      const bytes = Array.from(gz).map((b) => `0x${b.toString(16).padStart(2, '0')}`)
      // Format: 16 bytes per line
      const lines: string[] = []
      for (let i = 0; i < bytes.length; i += 16) {
        lines.push('  ' + bytes.slice(i, i + 16).join(', '))
      }

      const header = [
        '#pragma once',
        '',
        '// Auto-generated by vite build — do not edit manually',
        '// Rebuild with: cd frontend/app && pnpm build',
        '',
        '#include <cstddef>',
        '#include <cstdint>',
        '',
        '#ifdef ARDUINO',
        '#include <pgmspace.h>',
        '#else',
        '#ifndef PROGMEM',
        '#define PROGMEM',
        '#endif',
        '#endif',
        '',
        'namespace esphome {',
        'namespace elero {',
        '',
        'const uint8_t ELERO_WEB_UI_GZ[] PROGMEM = {',
        lines.join(',\n'),
        '};',
        '',
        `const size_t ELERO_WEB_UI_GZ_LEN = ${gz.length};`,
        '',
        '}  // namespace elero',
        '}  // namespace esphome',
        '',
      ].join('\n')

      writeFileSync(headerPath, header)
      console.log(`\n  Generated elero_web_ui.h: ${(html.length / 1024).toFixed(1)} KB -> ${(gz.length / 1024).toFixed(1)} KB gzipped\n`)
    },
  }
}

export default defineConfig({
  plugins: [
    preact(),
    tailwindcss(),
    viteSingleFile(),
    eleroGzipHeader(),
    {
      name: 'log-proxy-target',
      configureServer() {
        console.log(`\n  ➜  WebSocket proxy: ${deviceTarget}\n`)
      },
    },
  ],
  resolve: {
    alias: {
      '@': resolve(import.meta.dirname, './src'),
      'react': 'preact/compat',
      'react-dom': 'preact/compat',
      'react/jsx-runtime': 'preact/jsx-runtime',
    },
  },
  server: {
    port: 3000,
    proxy: {
      '/elero/ws': {
        target: deviceTarget,
        ws: true,
        rewriteWsOrigin: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    minify: 'esbuild',
    target: 'es2020',
  },
})
